# IQR-Interquartile Range

In [1]:
from Univariate import Univariate
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
quan,qual=Univariate.QuanQual(dataset)

In [5]:
quan,qual

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [6]:
#mean for specific column
dataset["ssc_p"].mean()

67.30339534883721

In [7]:
#median for specific column
dataset["ssc_p"].median()

67.0

In [8]:
#mode for specific column without 0
dataset["ssc_p"].mode()

0    62.0
dtype: float64

In [9]:
#mode for specific column with 0
dataset["ssc_p"].mode()[0]

62.0

In [10]:
#describe function will give only below values not median,mode
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [11]:
descriptive=pd.DataFrame()

In [12]:
descriptive #if we didn't mention any coumns and rows_index name, then pd.DataFrame will give without any row and cloumn like below

Empty DataFrame
Columns: []
Index: []

In [13]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [14]:
descriptive #we have mentioned only index name and cloumns name, so it will give empty list like below

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [15]:
descriptive["hsc_p"]["Median"]=0

In [16]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN     0      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [17]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()

In [18]:
descriptive #we have assigned mean value only in for loop, so we can see mean value for quan cloumns

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   NaN      NaN      NaN      NaN      NaN      NaN     NaN
Mode     NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [19]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()

In [20]:
descriptive

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   108       67       65       66       71       62  265000
Mode     NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [21]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]

In [22]:
descriptive

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   108       67       65       66       71       62  265000
Mode       1       62       63       65       60     56.7  300000

In [23]:
import numpy as np

In [24]:
np.percentile(dataset["salary"],25) #salary cloumn we have null values , so as of now we will use describe (describe will calculate only non-null values)

nan

In [25]:
np.percentile(dataset["mba_p"],25)

57.945

In [26]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=np.percentile(dataset[columnName],25)

In [27]:
descriptive #as we said earlier, as of now we can use describe function

        sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean      108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median    108       67       65       66       71       62  265000
Mode        1       62       63       65       60     56.7  300000
Q1:25%   54.5     60.6     60.9       61       60   57.945     NaN
Q2:50%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q3:75%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q4:100%   NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [28]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]

In [29]:
descriptive

         sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean       108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median     108       67       65       66       71       62  265000
Mode         1       62       63       65       60     56.7  300000
Q1:25%    54.5     60.6     60.9       61       60   57.945  240000
Q2:50%     108       67       65       66       71       62  265000
Q3:75%   161.5     75.7       73       72     83.5   66.255  300000
Q4:100%    215     89.4     97.7       91       98    77.89  940000

In [34]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%",
                               "IQR","1.5Rule","Lesser","Greater","Min","Max"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5Rule"]=1.5*descriptive[columnName]["IQR"]
    descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5Rule"]
    descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5Rule"]
    descriptive[columnName]["Min"]=dataset[columnName].min()
    descriptive[columnName]["Max"]=dataset[columnName].max()

In [35]:
descriptive

         sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean       108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median     108       67       65       66       71       62  265000
Mode         1       62       63       65       60     56.7  300000
Q1:25%    54.5     60.6     60.9       61       60   57.945  240000
Q2:50%     108       67       65       66       71       62  265000
Q3:75%   161.5     75.7       73       72     83.5   66.255  300000
Q4:100%    215     89.4     97.7       91       98    77.89  940000
IQR        107     15.1     12.1       11     23.5     8.31   60000
1.5Rule  160.5    22.65    18.15     16.5    35.25   12.465   90000
Lesser    -106    37.95    42.75     44.5    24.75    45.48  150000
Greater    322    98.35    91.15     88.5   118.75    78.72  390000
Min          1    40.89       37       50       50    51.21  200000
Max        215     89.4     97.7       91       98    77.89  940000