# Replacing Outliers and Frequency

In [1]:
from Univariate import Univariate
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
quan,qual=Univariate.QuanQual(dataset)

In [5]:
quan,qual

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [6]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%",
                               "IQR","1.5Rule","Lesser","Greater","Min","Max"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5Rule"]=1.5*descriptive[columnName]["IQR"]
    descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5Rule"]
    descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5Rule"]
    descriptive[columnName]["Min"]=dataset[columnName].min()
    descriptive[columnName]["Max"]=dataset[columnName].max()

In [7]:
descriptive

         sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean       108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median     108       67       65       66       71       62  265000
Mode         1       62       63       65       60     56.7  300000
Q1:25%    54.5     60.6     60.9       61       60   57.945  240000
Q2:50%     108       67       65       66       71       62  265000
Q3:75%   161.5     75.7       73       72     83.5   66.255  300000
Q4:100%    215     89.4     97.7       91       98    77.89  940000
IQR        107     15.1     12.1       11     23.5     8.31   60000
1.5Rule  160.5    22.65    18.15     16.5    35.25   12.465   90000
Lesser    -106    37.95    42.75     44.5    24.75    45.48  150000
Greater    322    98.35    91.15     88.5   118.75    78.72  390000
Min          1    40.89       37       50       50    51.21  200000
Max        215     89.4     97.7       91       98    77.89  940000

In [8]:
lesser=[]
greater=[]

for columnName in quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
        lesser.append(columnName)
    if(descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
        greater.append(columnName)

In [9]:
lesser

['hsc_p']

In [10]:
greater

['hsc_p', 'degree_p', 'salary']

In [11]:
for column in lesser:
    dataset[column][dataset[column]<descriptive[column]["Lesser"]]=descriptive[column]["Lesser"]
for column in greater:
    dataset[column][dataset[column]>descriptive[column]["Greater"]]=descriptive[column]["Greater"]

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [12]:
lesser1=[]
greater2=[]

for columnName in quan:
    if(descriptive[columnName]["Lesser"]>descriptive[columnName]["Min"]):
        lesser.append(columnName)
    if(descriptive[columnName]["Greater"]<descriptive[columnName]["Q4:100%"]):
        greater.append(columnName)

In [13]:
lesser1

[]

In [14]:
greater2

[]

In [15]:
dataset["ssc_p"].value_counts()

62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
80.60     1
65.20     1
80.40     1
59.96     1
78.50     1
Name: ssc_p, Length: 103, dtype: int64

In [16]:
freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative Frequency","Cusum"])

In [17]:
freqTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative Frequency, Cusum]
Index: []

In [18]:
freqTable["Unique_Values"]=dataset["ssc_p"].value_counts().index
freqTable["Frequency"]=dataset["ssc_p"].value_counts().values
freqTable["Relative Frequency"]=(freqTable["Frequency"]/103)
freqTable["Cusum"]=freqTable["Relative Frequency"].cumsum()

In [19]:
freqTable

     Unique_Values  Frequency  Relative Frequency     Cusum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            52.00          9            0.087379  0.378641
4            73.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           80.60          1            0.009709  2.048544
99           65.20          1            0.009709  2.058252
100          80.40          1            0.009709  2.067961
101          59.96          1            0.009709  2.077670
102          78.50          1            0.009709  2.087379

[103 rows x 4 columns]

In [20]:
def freqTable(colunName,dataset):
    freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative Frequency","Cusum"])
    freqTable["Unique_Values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative Frequency"]=(freqTable["Frequency"]/103)
    freqTable["Cusum"]=freqTable["Relative Frequency"].cumsum()
    return freqTable

In [21]:
freqTable("",dataset)

    Unique_Values  Frequency  Relative Frequency     Cusum
0        300000.0         22            0.213592  0.213592
1        250000.0         18            0.174757  0.388350
2        390000.0         15            0.145631  0.533981
3        240000.0         15            0.145631  0.679612
4        260000.0          7            0.067961  0.747573
5        200000.0          6            0.058252  0.805825
6        360000.0          6            0.058252  0.864078
7        265000.0          6            0.058252  0.922330
8        220000.0          5            0.048544  0.970874
9        275000.0          5            0.048544  1.019417
10       210000.0          4            0.038835  1.058252
11       270000.0          4            0.038835  1.097087
12       216000.0          3            0.029126  1.126214
13       350000.0          3            0.029126  1.155340
14       230000.0          2            0.019417  1.174757
15       218000.0          2            0.019417  1.194175
16       252000.0          2            0.019417  1.213592
17       236000.0          2            0.019417  1.233010
18       204000.0          2            0.019417  1.252427
19       280000.0          2            0.019417  1.271845
20       276000.0          2            0.019417  1.291262
21       290000.0          1            0.009709  1.300971
22       336000.0          1            0.009709  1.310680
23       264000.0          1            0.009709  1.320388
24       287000.0          1            0.009709  1.330097
25       380000.0          1            0.009709  1.339806
26       295000.0          1            0.009709  1.349515
27       340000.0          1            0.009709  1.359223
28       233000.0          1            0.009709  1.368932
29       225000.0          1            0.009709  1.378641
30       255000.0          1            0.009709  1.388350
31       268000.0          1            0.009709  1.398058
32       320000.0          1            0.009709  1.407767
33       231000.0          1            0.009709  1.417476
34       285000.0          1            0.009709  1.427184
35       278000.0          1            0.009709  1.436893

In [22]:
dataset["ssc_p"].skew()

-0.13264949031456927

In [23]:
dataset["ssc_p"].kurtosis()

-0.6075102066986688

In [25]:
def Univariate(dataset,quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%",
                               "Q3:75%","99%","Q4:100%","IQR","1.5rule","Lesser","Greater",
                                    "Min","Max","kurtosis","skew"],columns=quan)
    for columnName in quan:
        descriptive[columnName]["Mean"]=dataset[columnName].mean()
        descriptive[columnName]["Median"]=dataset[columnName].median()
        descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
        descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
        descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
        descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
        descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
        descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
        descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
        descriptive[columnName]["Min"]=dataset[columnName].min()
        descriptive[columnName]["Max"]=dataset[columnName].max()
        descriptive[columnName]["kurtosis"]=dataset[columnName].kurtosis()
        descriptive[columnName]["skew"]=dataset[columnName].skew()
    return descriptive

In [26]:
Univariate(dataset,quan)

          sl_no     ssc_p      hsc_p   degree_p   etest_p     mba_p    salary
Mean        108   67.3034    66.3347    66.3586   72.1006   62.2782    277649
Median      108        67         65         66        71        62    265000
Mode          1        62         63         65        60      56.7    300000
Q1:25%     54.5      60.6       60.9         61        60    57.945    240000
Q2:50%      108        67         65         66        71        62    265000
Q3:75%    161.5      75.7         73         72      83.5    66.255    300000
99%         NaN       NaN        NaN        NaN       NaN       NaN       NaN
Q4:100%     215      89.4      91.15       88.5        98     77.89    390000
IQR         107      15.1       12.1         11      23.5      8.31     60000
1.5rule   160.5     22.65      18.15       16.5     35.25    12.465     90000
Lesser     -106     37.95      42.75       44.5     24.75     45.48    150000
Greater     322     98.35      91.15       88.5    118.75     78.72    390000
Min           1     40.89      42.75         50        50     51.21    200000
Max         215      89.4      91.15       88.5        98     77.89    390000
kurtosis   -1.2  -0.60751  0.0869008 -0.0974897  -1.08858 -0.470723 -0.239837
skew          0 -0.132649   0.162611   0.204164  0.282308  0.313576    0.8067

# Variance and Std variance

In [27]:
dataset["ssc_p"].var()

117.2283767354923

In [28]:
dataset["ssc_p"].std()

10.827205398231452

In [31]:
def Univariate(dataset,quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%",
                               "Q3:75%","99%","Q4:100%","IQR","1.5rule","Lesser","Greater",
                                    "Min","Max","kurtosis","skew","Var","Std"],columns=quan)
    for columnName in quan:
        descriptive[columnName]["Mean"]=dataset[columnName].mean()
        descriptive[columnName]["Median"]=dataset[columnName].median()
        descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
        descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
        descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
        descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
        descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
        descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
        descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
        descriptive[columnName]["Min"]=dataset[columnName].min()
        descriptive[columnName]["Max"]=dataset[columnName].max()
        descriptive[columnName]["kurtosis"]=dataset[columnName].kurtosis()
        descriptive[columnName]["skew"]=dataset[columnName].skew()
        descriptive[columnName]["Var"]=dataset[columnName].var()
        descriptive[columnName]["Std"]=dataset[columnName].std()
    return descriptive

In [32]:
Univariate(dataset,quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108,67.3034,66.3347,66.3586,72.1006,62.2782,277649
Median,108,67,65,66,71,62,265000
Mode,1,62,63,65,60,56.7,300000
Q1:25%,54.5,60.6,60.9,61,60,57.945,240000
Q2:50%,108,67,65,66,71,62,265000
Q3:75%,161.5,75.7,73,72,83.5,66.255,300000
99%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q4:100%,215,89.4,91.15,88.5,98,77.89,390000
IQR,107,15.1,12.1,11,23.5,8.31,60000
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000
Lesser,-106,37.95,42.75,44.5,24.75,45.48,150000
Greater,322,98.35,91.15,88.5,118.75,78.72,390000
Min,1,40.89,42.75,50,50,51.21,200000
Max,215,89.4,91.15,88.5,98,77.89,390000
kurtosis,-1.2,-0.60751,0.0869008,-0.0974897,-1.08858,-0.470723,-0.239837
skew,0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
Var,3870,117.228,112.064,53.6047,176.251,34.0284,2.9446e+09
Std,62.2093,10.8272,10.586,7.32152,13.276,5.83338,54264.1